[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "automate_subcontracting"
authors = [
    { name = "Rinix Automation Pvt Ltd", email = "admin@rinix.in" }
]
description = "Automate Subcontracting ERPNext"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
version = "1.0.0"

dependencies = [
    "frappe",
]

[tool.bench.app]
required_apps = ["frappe", "erpnext"]
